services:
  db:
    container_name: ht_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: h34lThTr4ck3r
      POSTGRES_USER: htuser
      POSTGRES_DB: htracker
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data    